version: "3.4"
services:
  mysql:
    build: ../../tools/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sample_database
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  api-server:
    restart: always
    build: ../../app/apiServer/target/docker/stage
    ports:
      - 18080:18080
    logging:
      driver: gcplogs
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      - mysql
